version = 1
SPDX-PackageName = "net.splitcells.network"
SPDX-PackageSupplier = "Mārtiņš Avots <martins.avots@splitcells.net>"
SPDX-PackageDownloadLocation = "https://splitcells.net"

# The REUSE.toml needs a rule, as otherwise https://api.reuse.software seems to have a problem with this file.
[[annotations]]
path = "REUSE.toml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "EPL-2.0 OR GPL-2.0-or-later"

[[annotations]]
path = "src/main/resources/chart.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/chartjs-plugin-datasource.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/cin/js/three.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/cin/js/controls/OrbitControls.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/css/dragula.min.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/css/jquery-fancytree-all-deps.min.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/css/jquery-fancytree-all-deps.min.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/css/tabulator.min.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/chart.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/chartjs-plugin-datasource.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/codemirror-editor-bundle.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/dragula.min.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/jquery-fancytree-all-deps.min.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/jquery-fancytree-all-deps-injection.min.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/mermaid.min.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/tabulator.injection.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/tabulator.min.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/math-jax/es5/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Contributors To The `net.splitcells.*` Projects"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/js/highlight.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2006, Ivan Sagalaev."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/main/resources/html/net/splitcells/website/css/highlight.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2006, Ivan Sagalaev."
SPDX-License-Identifier = "MIT"